export default {
  UPDATE_DATE: "UPDATE_DATE",
  GET_ESTRENOS: "GET_ESTRENOS",
  _FULFILLED: "_FULFILLED",
  // GET_ESTRENOS_FULFILLED: "GET_ESTRENOS_FULFILLED",
  // GET_ESTRENOS_PENDING: "GET_ESTRENOS_PENDING",
  // GET_ESTRENOS_REJECTED: "GET_ESTRENOS_REJECTED",
  //Popular
  GET_POPULAR: "GET_POPULAR",
  // GET_POPULAR_FULFILLED: "GET_POPULAR_FULFILLED",
  // GET_POPULAR_PENDING: "GET_CPOPULAR_PENDING",
  // GET_POPULAR_REJECTED: "GET_POPULAR_REJECTED",
  //Creditos
  GET_CREDITOS: "GET_CREDITOS",
  // GET_CREDITOS_FULFILLED: "GET_CREDITOS_FULFILLED",
  // GET_CREDITOS_PENDING: "GET_CREDITOS_PENDING",
  // GET_CREDITOS_REJECTED: "GET_CREDITOS_REJECTED",
  GET_DETALLES: "GET_DETALLES",
  
  _PENDING: "_PENDING",
  _REJECTED: "_REJECTED"
}